[package]
name = "bitcoin-whitepaper"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_decimal = "1.37.2"
sha2 = "0.10.9"
k256 = {version = "0.13.4", features = ["ecdsa"]}
rand_core = "0.9.3"
rand = "0.8.5"
